# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://hlafortu.github.io/pypnc/"

git_url = "https://github.com/hlafortu/pypnc/tree/master/"

def custom_doc_links(name): return None
